# -*- ruby -*-

# Class path
$:.unshift(File.dirname(__FILE__))

# Libraries
require 'rubygems'
require 'hoe'
require 'version_bumper'

# Hoe Spec
Hoe.spec 'poc-server' do
  self.version        = File.read(File.join(File.dirname(__FILE__),'VERSION'))
  self.developer      'Sean Humbarger', 'sean.humbarger@issinc.com'
  self.license        'MIT'
  self.readme_file    = 'README.md'
  self.extra_deps     = [
    ['thin',                '~> 1.6'    ],
    ['highline',            '~> 1.6'    ],
    ['sinatra',             '~> 1.4'    ],
    ['gli',                 '~> 2.12'   ],
    ['sinatra-namespace',   '~> 1.0'    ],
  	['ruby-enum',           '~> 0.4'    ],
  	['json',                '~> 1.8'    ],
    ['poc-logger',          '~> 1.0'    ],
    ['poc-dao',             '~> 1.0'    ]
  ]
  self.extra_dev_deps = [
    ['yard',            '~> 0.8.7'],
    ['yard-sinatra',    '~> 1.0'  ],
  	['version_bumper',  '~> 0.3'  ],
  	['bundler',         '~> 1.7'  ],
  	['minitest',        '~> 5.4'  ],
    ['rest-client',     '~> 1.6'  ]
  ]

end

# vim: syntax=ruby
