# -*- ruby -*-

# Class path
$:.unshift(File.dirname(__FILE__))

# Libraries
require 'rubygems'
require 'hoe'
require 'version_bumper'

# Hoe Spec
Hoe.spec "poc-logger" do
  self.version        = File.read(File.join(File.dirname(__FILE__),'VERSION'))
  self.developer      'Sean Humbarger', 'sean.humbarger@gmail.com'
  self.description    = 'Common Logger Library for POC services.'
  self.summary        = 'Common Logger Library.'
  self.license        'MIT'
  self.readme_file    = 'README.md'
  self.extra_deps     = []
  self.extra_dev_deps = [
    ['yard',            '~> 0.8.7'],
  	['version_bumper',  '~> 0.3'  ],
  	['bundler',         '~> 1.7'  ],
  	['minitest',        '~> 5.4'  ]
  ]

end

# vim: syntax=ruby
